services:
  client:
    depends_on:
      - server
    build:
      context: .
      dockerfile: client-dev.Dockerfile
    ports:
      - 5173:5173
    profiles:
      - all
    environment:
      API_URL: http://localhost:8080
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    develop:
      # we specify the files to watch for changes
      watch:
        # it'll watch for changes in package.json and package-lock.json and rebuild the container if there are any changes
        - path: ./client/package.json
          action: rebuild
        - path: ./client/pnpm-lock.yaml
          action: rebuild
        # it'll watch for changes in the frontend directory and sync the changes with the container real time
        - path: ./client
          target: /app
          action: sync
          
  server:
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: server-dev.Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      POSTGRES_DATABASE: pushme
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      REDIS_URL: redis://default:default@redis:6379/0

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: pushme
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis
    environment:
      REDIS_PASSWORD: default
  
  adminer:
    image: adminer
    ports:
      - 8081:8080
