services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - 8080:8080
    environment:
      MONGODB_DATABASE: pushme
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: root
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
