services:
  server:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - 8080:8080
    environment:
      POSTGRES_DATABASE: pushme
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: pushme
      POSTGRES_PASSWORD: postgres
